name: Lodestar
version: 1.0.0
author: harrison.page
main: love.toad.Lodestar
api-version: 1.21
description: Show player coordinates, compass direction and % remaining for day/night in bossbar
commands:
   lodestar:
      description: Show coords, direction and remaining day/night
      usage: /lodestar
